version: '3'

services:
    app:
        build: .
        container_name: adoorei_app
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_USERNAME=adoorei
            - DB_DATABASE=adoorei
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
            - dbtest
    db:
        image: mariadb:10.11.3
        container_name: adoorei_db
        ports:
            - 33068:3306
        volumes:
            - .db/:/var/lib/mysql
        environment:
            MYSQL_DATABASE: adoorei
            MYSQL_USER: adoorei
            MYSQL_PASSWORD: adoorei
            MYSQL_ROOT_PASSWORD: adoorei

    dbtest:
        image: mariadb:10.11.3
        container_name: adoorei_dbtest
        ports:
            - 33069:3306
        environment:
            MYSQL_DATABASE: adoorei_test
            MYSQL_USER: adoorei_test
            MYSQL_PASSWORD: adoorei_test
            MYSQL_ROOT_PASSWORD: adoorei_test

