version: '3'

services:
    app:
        build: .
        container_name: adoorei_app
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_USERNAME=adoorei
            - DB_DATABASE=adoorei
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
    db:
        image: mariadb:10.11.3
        container_name: adoorei_db
        ports:
            - 33068:3306
#        command: --max-connections=1024 --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
        volumes:
            - .db/:/var/lib/mysql
        environment:
            MYSQL_DATABASE: adoorei
            MYSQL_USER: adoorei
            MYSQL_PASSWORD: adoorei
            MYSQL_ROOT_PASSWORD: adoorei

